// DO NOT EDIT THIS CONTENT.
// This content is locked and must match the original website exactly.
// Only explicit written approval permits changes.
export const career = {
  "key": "career",
  "name": "Career",
  "route": "/career",
  "url": "https://mediumpurple-ant-531485.hostingersite.com/career/",
  "image": "/assets/city-consulting.jpg",
  "start": "Careers",
  "currentUrl": "https://mediumpurple-ant-531485.hostingersite.com/career/",
  "title": "Career – mediumpurple-ant-531485.hostingersite.com",
  "description": "Join a team where transformation is real, responsibility comes early,",
  "lines": [
    "Skip to content",
    "Follow us:",
    "info@yourbrand.com",
    "+91 98765 43210",
    "Arete Partners",
    "Home",
    "About",
    "Services ▾",
    "Services Portfolio",
    "Strategy & Operations services by theme",
    "All Services",
    "Overview of our Strategy & Operations offerings across growth, operations and corporate functions.",
    "Growth & Transformation",
    "Vision, strategy, operating models and growth execution for leaders and boards.",
    "Operational Excellence",
    "Cost, quality and productivity improvement through Lean, Gen AI and digital.",
    "Process Advisory",
    "Process design, metrics, analytics and QMS / TQM maturity assessments.",
    "Service Delivery",
    "Customer strategy, journeys and service delivery design & measurement.",
    "Corporate Function Transformation",
    "From fragmented support functions to an integrated, data-driven corporate backbone.",
    "Strategy & Operations",
    "Designing growth, margin and resilience together",
    "Our services span the full Strategy & Operations stack – from growth strategy and operating models",
    "to Lean, digital, and corporate function transformation – with measurable impact.",
    "Growth",
    "OpEx",
    "Process",
    "Customer",
    "Corporate Backbone",
    "View all services",
    "Discuss your priorities →",
    "Industries ▾",
    "Industry Pages",
    "Choose a sector to explore solutions",
    "Pharmaceutical",
    "Quality, compliance, throughput, cost and reliability.",
    "Manufacturing",
    "Lean systems, productivity, stable operations at scale.",
    "Healthcare",
    "Patient experience, capacity, and operational resilience.",
    "Insurance",
    "Claims speed, trust, cost discipline, digital enablement.",
    "Aerospace & Defence",
    "High-stakes delivery with quality and traceability.",
    "Automotive",
    "EV shift, supply volatility, productivity, speed.",
    "Global Capability Centers",
    "Value platforms, governance, productivity at scale.",
    "Education",
    "Future-ready workforce, capability and ecosystem impact.",
    "Featured",
    "Explore transformation playbooks by sector",
    "Practical, system-level work across strategy, operating models, digital enablement,",
    "capability building, and measurable outcomes.",
    "Strategy",
    "Operating Model",
    "Digital",
    "ESG",
    "OpEx",
    "Talk to us",
    "Request consultation →",
    "Career",
    "Contact",
    "Services",
    "Book Consultation",
    "Y",
    "YourBrand Consulting",
    "Menu",
    "Home →",
    "About →",
    "Services ⌄",
    "All Services",
    "Growth & Transformation",
    "Operational Excellence",
    "Process Advisory",
    "Service Delivery",
    "Corporate Function Transformation",
    "Industries ⌄",
    "Pharmaceutical",
    "Manufacturing",
    "Healthcare",
    "Insurance",
    "Aerospace & Defence",
    "Automotive",
    "GCC",
    "Education",
    "Career →",
    "Contact →",
    "View Services",
    "Book Consultation →",
    "Follow us:",
    "Facebook",
    "Twitter",
    "Youtube",
    "info@aretepartners.com",
    "+91 9876543210",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "+1 (212)-695-1962",
    "info@elementskit.com",
    "463 7th Ave, NY 10018, USA",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "placeholder.png",
    "X",
    "Careers",
    "Be a part of our journey",
    "Join a team where transformation is real, responsibility comes early,",
    "and the work you do shapes organisations, industries, and lives.",
    "Explore opportunities",
    "Life at [Your Firm Name]",
    "Why Join Us",
    "Build a career that creates real, lasting change.",
    "When you join [Your Firm Name], you don’t just work on projects. You help shape",
    "organisations, enable leaders, and build capabilities that outlast any engagement.",
    "🌍",
    "Global impact, local heart",
    "Work on transformations that drive growth and sustainability for clients across the globe,",
    "while staying grounded in a culture that values purpose and people.",
    "🚀",
    "Growth without limits",
    "From Lean Six Sigma to AI, ESG, and Industry 4.0, you’ll get structured opportunities",
    "to deepen your expertise and expand your horizons across disciplines.",
    "🤝",
    "Extended family, not just colleagues",
    "We operate as one team. You’ll be empowered, supported, and trusted—with ownership to",
    "experiment, innovate, and deliver results that truly matter.",
    "💡",
    "Tech + human-centric approach",
    "Shape the future using advanced digital tools and analytics, while keeping the human",
    "insight and empathy that make change real and sustainable.",
    "🌱",
    "Sustainable value creation",
    "Every project is designed to create lasting value—for our clients, their stakeholders,",
    "and society. Your work contributes to outcomes that endure.",
    "Life at [Your Firm Name]",
    "A place to grow fast, do real work, and stay grounded.",
    "Life here is built around three things: meaningful client impact, deep learning, and teams",
    "that genuinely have your back.",
    "Purpose driven",
    "High pace",
    "Learning first",
    "Global collaboration",
    "Ownership",
    "🎯",
    "Purpose-driven culture",
    "Everything we do is anchored in client success and meaningful impact. You’ll see the",
    "effect of your work in real business outcomes, not just in slide decks.",
    "⚡",
    "Agility in action",
    "You’ll thrive in a fast-paced environment where change is treated as opportunity,",
    "not obstacle — with teams that move quickly and decide clearly.",
    "📚",
    "Learning & growth built-in",
    "Structured career paths, mentorship, and continuous development programs keep you",
    "future-ready — from foundational consulting skills to advanced digital, Lean,",
    "and leadership capabilities.",
    "Think curated learning journeys, not random trainings — designed so every project stretches",
    "you just enough.",
    "🌐",
    "Collaboration beyond borders",
    "Work with global talent pools, industry leaders, and ecosystem partners — across regions,",
    "sectors, and disciplines.",
    "🏁",
    "Ownership from day one",
    "We reward initiative, innovation, and accountability. You’ll get real responsibility",
    "early, with the support to turn good ideas into visible outcomes.",
    "Our values in action",
    "What we stand for when we show up to work.",
    "These are the principles that shape how we think, decide, and deliver — with clients,",
    "with each other, and in the way we grow the firm.",
    "🎯",
    "Purpose",
    "Anchor every decision in long-term impact — for our clients, their stakeholders,",
    "and the communities we serve.",
    "⚡",
    "Agility",
    "Adapt fast, act smart. We test, learn, and move quickly without losing",
    "discipline or clarity.",
    "🤝",
    "Collaboration",
    "Harness collective intelligence — across teams, clients, and partners —",
    "to solve problems that matter.",
    "🔐",
    "Trust",
    "Deliver with integrity, transparency, and follow-through so people can rely",
    "on what we say and do.",
    "⭐",
    "Excellence",
    "Always go the extra mile — in the quality of our thinking, our execution,",
    "and the experience we create.",
    "Career pathways",
    "Where you can grow with us",
    "We’re always looking for problem-solvers, innovators, and leaders who want to build",
    "real capability — and deliver outcomes that last.",
    "Impact",
    "Learning",
    "Ownership",
    "Client-side",
    "📈",
    "Growth & Strategy Consulting",
    "Shape strategic direction, operating models, and execution roadmaps with measurable outcomes.",
    "Strategy • TOM • Governance",
    "🤖",
    "Tech-Enabled Transformation",
    "Enable digital transformation through data, automation, AI, and modern platforms — grounded in execution.",
    "Digital • Analytics • AI",
    "🌿",
    "ESG & Sustainability",
    "Build resilient, responsible organisations through ESG strategy, reporting, and sustainability programs.",
    "ESG • Reporting • Value",
    "⚙️",
    "Operational Excellence",
    "Drive productivity, quality, and speed using Lean, continuous improvement, and Industry 4.0 thinking.",
    "Lean • CI • Performance",
    "🧩",
    "Business Process Advisory",
    "Design better processes, shared services, and governance — building systems that scale.",
    "Shared Services • BPM • KPIs",
    "🧭",
    "Open Roles Across Functions",
    "We also hire across research, delivery, program management, and capability building.",
    "PMO • Delivery • Enablement",
    "Your journey with us",
    "From day one, you’re part of the real work.",
    "From Day 1, you’ll be on live projects, mentored by global experts, and equipped",
    "with tools that connect strategy to execution — so you see the impact of your work",
    "in real outcomes, not just presentations.",
    "Ready to create something extraordinary?",
    "Join us to transform strategy into results that last.",
    "Apply now →",
    "View role pathways",
    "No perfect CV? If you’re curious, driven, and collaborative, we still want to hear from you.",
    "All rights reserved"
  ],
  "contentLines": [
    "Careers",
    "Be a part of our journey",
    "Join a team where transformation is real, responsibility comes early,",
    "and the work you do shapes organisations, industries, and lives.",
    "Explore opportunities",
    "Life at [Your Firm Name]",
    "Why Join Us",
    "Build a career that creates real, lasting change.",
    "When you join [Your Firm Name], you don’t just work on projects. You help shape",
    "organisations, enable leaders, and build capabilities that outlast any engagement.",
    "🌍",
    "Global impact, local heart",
    "Work on transformations that drive growth and sustainability for clients across the globe,",
    "while staying grounded in a culture that values purpose and people.",
    "🚀",
    "Growth without limits",
    "From Lean Six Sigma to AI, ESG, and Industry 4.0, you’ll get structured opportunities",
    "to deepen your expertise and expand your horizons across disciplines.",
    "🤝",
    "Extended family, not just colleagues",
    "We operate as one team. You’ll be empowered, supported, and trusted—with ownership to",
    "experiment, innovate, and deliver results that truly matter.",
    "💡",
    "Tech + human-centric approach",
    "Shape the future using advanced digital tools and analytics, while keeping the human",
    "insight and empathy that make change real and sustainable.",
    "🌱",
    "Sustainable value creation",
    "Every project is designed to create lasting value—for our clients, their stakeholders,",
    "and society. Your work contributes to outcomes that endure.",
    "Life at [Your Firm Name]",
    "A place to grow fast, do real work, and stay grounded.",
    "Life here is built around three things: meaningful client impact, deep learning, and teams",
    "that genuinely have your back.",
    "Purpose driven",
    "High pace",
    "Learning first",
    "Global collaboration",
    "Ownership",
    "🎯",
    "Purpose-driven culture",
    "Everything we do is anchored in client success and meaningful impact. You’ll see the",
    "effect of your work in real business outcomes, not just in slide decks.",
    "⚡",
    "Agility in action",
    "You’ll thrive in a fast-paced environment where change is treated as opportunity,",
    "not obstacle — with teams that move quickly and decide clearly.",
    "📚",
    "Learning & growth built-in",
    "Structured career paths, mentorship, and continuous development programs keep you",
    "future-ready — from foundational consulting skills to advanced digital, Lean,",
    "and leadership capabilities.",
    "Think curated learning journeys, not random trainings — designed so every project stretches",
    "you just enough.",
    "🌐",
    "Collaboration beyond borders",
    "Work with global talent pools, industry leaders, and ecosystem partners — across regions,",
    "sectors, and disciplines.",
    "🏁",
    "Ownership from day one",
    "We reward initiative, innovation, and accountability. You’ll get real responsibility",
    "early, with the support to turn good ideas into visible outcomes.",
    "Our values in action",
    "What we stand for when we show up to work.",
    "These are the principles that shape how we think, decide, and deliver — with clients,",
    "with each other, and in the way we grow the firm.",
    "🎯",
    "Purpose",
    "Anchor every decision in long-term impact — for our clients, their stakeholders,",
    "and the communities we serve.",
    "⚡",
    "Agility",
    "Adapt fast, act smart. We test, learn, and move quickly without losing",
    "discipline or clarity.",
    "🤝",
    "Collaboration",
    "Harness collective intelligence — across teams, clients, and partners —",
    "to solve problems that matter.",
    "🔐",
    "Trust",
    "Deliver with integrity, transparency, and follow-through so people can rely",
    "on what we say and do.",
    "⭐",
    "Excellence",
    "Always go the extra mile — in the quality of our thinking, our execution,",
    "and the experience we create.",
    "Career pathways",
    "Where you can grow with us",
    "We’re always looking for problem-solvers, innovators, and leaders who want to build",
    "real capability — and deliver outcomes that last.",
    "Impact",
    "Learning",
    "Ownership",
    "Client-side",
    "📈",
    "Growth & Strategy Consulting",
    "Shape strategic direction, operating models, and execution roadmaps with measurable outcomes.",
    "Strategy • TOM • Governance",
    "🤖",
    "Tech-Enabled Transformation",
    "Enable digital transformation through data, automation, AI, and modern platforms — grounded in execution.",
    "Digital • Analytics • AI",
    "🌿",
    "ESG & Sustainability",
    "Build resilient, responsible organisations through ESG strategy, reporting, and sustainability programs.",
    "ESG • Reporting • Value",
    "⚙️",
    "Operational Excellence",
    "Drive productivity, quality, and speed using Lean, continuous improvement, and Industry 4.0 thinking.",
    "Lean • CI • Performance",
    "🧩",
    "Business Process Advisory",
    "Design better processes, shared services, and governance — building systems that scale.",
    "Shared Services • BPM • KPIs",
    "🧭",
    "Open Roles Across Functions",
    "We also hire across research, delivery, program management, and capability building.",
    "PMO • Delivery • Enablement",
    "Your journey with us",
    "From day one, you’re part of the real work.",
    "From Day 1, you’ll be on live projects, mentored by global experts, and equipped",
    "with tools that connect strategy to execution — so you see the impact of your work",
    "in real outcomes, not just presentations.",
    "Ready to create something extraordinary?",
    "Join us to transform strategy into results that last.",
    "Apply now →",
    "View role pathways",
    "No perfect CV? If you’re curious, driven, and collaborative, we still want to hear from you.",
    "All rights reserved"
  ]
} as const;
