// DO NOT EDIT THIS CONTENT.
// This content is locked and must match the original website exactly.
// Only explicit written approval permits changes.
export const products = {
  "key": "products",
  "name": "Products",
  "route": "/products",
  "url": "https://mediumpurple-ant-531485.hostingersite.com/products/",
  "image": "/assets/banner-new.jpg",
  "start": "Products",
  "currentUrl": "https://mediumpurple-ant-531485.hostingersite.com/products/",
  "title": "Products – mediumpurple-ant-531485.hostingersite.com",
  "description": "Products",
  "lines": [
    "Skip to content",
    "Follow us:",
    "info@yourbrand.com",
    "+91 98765 43210",
    "Arete Partners",
    "Home",
    "About",
    "Services ▾",
    "Services Portfolio",
    "Strategy & Operations services by theme",
    "All Services",
    "Overview of our Strategy & Operations offerings across growth, operations and corporate functions.",
    "Growth & Transformation",
    "Vision, strategy, operating models and growth execution for leaders and boards.",
    "Operational Excellence",
    "Cost, quality and productivity improvement through Lean, Gen AI and digital.",
    "Process Advisory",
    "Process design, metrics, analytics and QMS / TQM maturity assessments.",
    "Service Delivery",
    "Customer strategy, journeys and service delivery design & measurement.",
    "Corporate Function Transformation",
    "From fragmented support functions to an integrated, data-driven corporate backbone.",
    "Strategy & Operations",
    "Designing growth, margin and resilience together",
    "Our services span the full Strategy & Operations stack – from growth strategy and operating models",
    "to Lean, digital, and corporate function transformation – with measurable impact.",
    "Growth",
    "OpEx",
    "Process",
    "Customer",
    "Corporate Backbone",
    "View all services",
    "Discuss your priorities →",
    "Industries ▾",
    "Industry Pages",
    "Choose a sector to explore solutions",
    "Pharmaceutical",
    "Quality, compliance, throughput, cost and reliability.",
    "Manufacturing",
    "Lean systems, productivity, stable operations at scale.",
    "Healthcare",
    "Patient experience, capacity, and operational resilience.",
    "Insurance",
    "Claims speed, trust, cost discipline, digital enablement.",
    "Aerospace & Defence",
    "High-stakes delivery with quality and traceability.",
    "Automotive",
    "EV shift, supply volatility, productivity, speed.",
    "Global Capability Centers",
    "Value platforms, governance, productivity at scale.",
    "Education",
    "Future-ready workforce, capability and ecosystem impact.",
    "Featured",
    "Explore transformation playbooks by sector",
    "Practical, system-level work across strategy, operating models, digital enablement,",
    "capability building, and measurable outcomes.",
    "Strategy",
    "Operating Model",
    "Digital",
    "ESG",
    "OpEx",
    "Talk to us",
    "Request consultation →",
    "Career",
    "Contact",
    "Services",
    "Book Consultation",
    "Y",
    "YourBrand Consulting",
    "Menu",
    "Home →",
    "About →",
    "Services ⌄",
    "All Services",
    "Growth & Transformation",
    "Operational Excellence",
    "Process Advisory",
    "Service Delivery",
    "Corporate Function Transformation",
    "Industries ⌄",
    "Pharmaceutical",
    "Manufacturing",
    "Healthcare",
    "Insurance",
    "Aerospace & Defence",
    "Automotive",
    "GCC",
    "Education",
    "Career →",
    "Contact →",
    "View Services",
    "Book Consultation →",
    "Follow us:",
    "Facebook",
    "Twitter",
    "Youtube",
    "info@aretepartners.com",
    "+91 9876543210",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "+1 (212)-695-1962",
    "info@elementskit.com",
    "463 7th Ave, NY 10018, USA",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "placeholder.png",
    "X",
    "Products",
    "All rights reserved"
  ],
  "contentLines": [
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "+1 (212)-695-1962",
    "info@elementskit.com",
    "463 7th Ave, NY 10018, USA",
    "Home",
    "About",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "placeholder.png",
    "X",
    "Products",
    "All rights reserved"
  ]
} as const;
