// DO NOT EDIT THIS CONTENT.
// This content is locked and must match the original website exactly.
// Only explicit written approval permits changes.
export const about = {
  "key": "about",
  "name": "About",
  "route": "/about",
  "currentUrl": "https://mediumpurple-ant-531485.hostingersite.com/about/",
  "source": "15-about.txt",
  "image": "/assets/city-consulting.jpg",
  "title": "About Us",
  "description": "A new-age consulting firm redefining growth, efficiency, and impact",
  "lines": [
    "About Us",
    "A new-age consulting firm redefining growth, efficiency, and impact",
    "We partner with leadership teams to translate strategy into executio",
    "— aligning people,",
    "processes, and technology to deliver measurable, lasting business outcomes.",
    "Talk to Us →",
    "Who We Are ↓",
    "n",
    "Purpose & Vision",
    "What we stand for — and where we’re going",
    "Our consulting philosophy is grounded i",
    "one belief: lasting transformatio",
    "happens",
    "whe",
    "strategy, execution, and people move together.",
    "Vision",
    "To be the consulting partner know",
    "for turning every client investment into a multiplier",
    "of growth, innovation, and lasting impact — powered by a team that thrives o",
    "making a difference.",
    "Purpose",
    "To transform businesses i",
    "ways that transform lives — enabling our clients,",
    "their customers, and our ow",
    "people to achieve more tha",
    "they imagined possible.",
    "Tagline",
    "Where revenue growth meets operational excellence and meaningful impact.",
    "Brand Promise",
    "We help organizations grow faster, operate smarter, and create lasting value — for their",
    "customers, employees, and stakeholders — turning every consulting dollar into a multiplier",
    "of measurable results.",
    "Core Belief",
    "Transformatio",
    "works best whe",
    "strategy meets executio",
    "— and whe",
    "people are at the heart of change.",
    "Talk to Us →",
    "Next: Who We Are ↓",
    "n",
    "ORIGIN STORY",
    "Built to deliver sustainable results",
    "It all bega",
    "with a bold question:",
    "How ca",
    "we work hand i",
    "hand with our clients to deliver sustainable results",
    "—where every consulting dollar becomes a multiplier of growth, innovation, and impact?",
    "Our answer was to create a model that fuses deep expertise with technology, and a delivery approach that scales globally while staying personal.",
    "01",
    "HAND-IN-HAND DELIVERY",
    "We work as a",
    "extensio",
    "of your leadership team — co-owning the problem, the plan, and the outcome.",
    "02",
    "DEEP EXPERTISE × TECH",
    "A model that fuses domai",
    "expertise with technology so executio",
    "is faster, smarter, and scalable.",
    "03",
    "GLOBAL SCALE, PERSONAL FEEL",
    "A globally scalable delivery approach that stays personal — ensuring clarity, continuity, and trust.",
    "n",
    "FOUNDATION",
    "Vision, progress, and culture",
    "Visio",
    "To be the consulting partner know",
    "for turning every client investment into a multiplier of growth,",
    "innovation, and lasting impact — powered by a team that thrives o",
    "making a difference.",
    "Progress Milestone",
    "I",
    "a short span, we’ve brought together exceptional global talent, industry-leading expertise, and a",
    "tech-enabled, integrated delivery model to help organizations achieve measurable results and enduring transformation.",
    "Team Culture",
    "Our team is united by a shared purpose, fueled by agility, and thrives o",
    "collaboration. We build trust through",
    "integrity, deliver excellence through discipline, and measure success by the lasting impact we create for our clients,",
    "their customers, and stakeholders.",
    "n",
    "Core Services",
    "What We Do — And How We Create Impact",
    "We help our clients grow faster, operate smarter, and create lasting value through:",
    "Growth & Strategy",
    "Driving revenue growth, market expansion, and competitive advantage.",
    "Shared Services & Global Capability Centers (GCC)",
    "Designing and scaling efficient, high-performing hubs.",
    "Tech-Enabled Transformatio",
    "Leveraging digital, automation, and analytics to reimagine operations.",
    "ESG & Value Creatio",
    "Embedding sustainability into business strategy for measurable impact.",
    "Business Process Advisory & Industry 4.0",
    "Streamlining processes, boosting productivity, and enabling innovation.",
    "Enablers",
    "Our services are backed by proprietary technology assets, prove",
    "methodologies,",
    "and a commitment to a trusted, secure, and compliant work environment—ensuring",
    "data integrity and client confidentiality at all times.",
    "n",
    "Who We Are",
    "A consulting partner built for lasting impact",
    "We are a consulting partner dedicated to driving growth, operational excellence,",
    "technology enablement, and sustainability.",
    "Working as a",
    "extensio",
    "of our clients’ teams, we support them from strategy to execution,",
    "delivering results that are sustainable, measurable, and lasting.",
    "Our missio",
    "is clear: make our clients successful and ear",
    "the privilege of being their Advisor for Life.",
    "By combining global talent, deep domai",
    "expertise, and proprietary technology assets,",
    "we deliver transformations that accelerate growth, strengthe",
    "resilience, and spark innovation.",
    "We operate i",
    "a trusted, secure, and compliant environment, ensuring confidentiality,",
    "data integrity, and uncompromising quality i",
    "everything we do.",
    "n",
    "Our 5 Core Principles — and the Impact We Deliver",
    "01",
    "Client-First Mindset",
    "→",
    "02",
    "Employee Engagement & Ownership",
    "→",
    "03",
    "Ownership for Excellence",
    "→",
    "04",
    "Deliver Sustainable Results",
    "→",
    "05",
    "Ensure Positive ROI",
    "→",
    "Core Principle",
    "Client-First Mindset",
    "01",
    "We put your priorities at the center of everything we do, aligning strategies with your vision.",
    "Measurable Impact: 95%+ client satisfactio",
    "scores, repeat engagements with over 80% of our clients, and measurable business KPI improvements withi",
    "the first 3–6 months."
  ]
} as const;
