// DO NOT EDIT THIS CONTENT.
// This content is locked and must match the original website exactly.
// Only explicit written approval permits changes.
export const career = {
  "key": "career",
  "name": "Career",
  "route": "/career",
  "currentUrl": "https://mediumpurple-ant-531485.hostingersite.com/career/",
  "source": "19-career.txt",
  "image": "/assets/city-consulting.jpg",
  "title": "Careers",
  "description": "Be a part of our journey",
  "lines": [
    "Careers",
    "Be a part of our journey",
    "Joi",
    "a team where transformatio",
    "is real, responsibility comes early,",
    "and the work you do shapes organisations, industries, and lives.",
    "Explore opportunities",
    "Life at [Your Firm Name]",
    "n",
    "Why Joi",
    "Us",
    "Build a career that creates real, lasting change.",
    "Whe",
    "you joi",
    "[Your Firm Name], you don’t just work o",
    "projects. You help shape",
    "organisations, enable leaders, and build capabilities that outlast any engagement.",
    "🌍",
    "Global impact, local heart",
    "Work o",
    "transformations that drive growth and sustainability for clients across the globe,",
    "while staying grounded i",
    "a culture that values purpose and people.",
    "🚀",
    "Growth without limits",
    "From Lea",
    "Six Sigma to AI, ESG, and Industry 4.0, you’ll get structured opportunities",
    "to deepe",
    "your expertise and expand your horizons across disciplines.",
    "🤝",
    "Extended family, not just colleagues",
    "We operate as one team. You’ll be empowered, supported, and trusted—with ownership to",
    "experiment, innovate, and deliver results that truly matter.",
    "💡",
    "Tech + human-centric approach",
    "Shape the future using advanced digital tools and analytics, while keeping the human",
    "insight and empathy that make change real and sustainable.",
    "🌱",
    "Sustainable value creatio",
    "Every project is designed to create lasting value—for our clients, their stakeholders,",
    "and society. Your work contributes to outcomes that endure.",
    "n",
    "Life at [Your Firm Name]",
    "A place to grow fast, do real work, and stay grounded.",
    "Life here is built around three things: meaningful client impact, deep learning, and teams",
    "that genuinely have your back.",
    "Purpose driven",
    "High pace",
    "Learning first",
    "Global collaboration",
    "Ownership",
    "🎯",
    "Purpose-drive",
    "culture",
    "Everything we do is anchored i",
    "client success and meaningful impact. You’ll see the",
    "effect of your work i",
    "real business outcomes, not just i",
    "slide decks.",
    "⚡",
    "Agility i",
    "actio",
    "You’ll thrive i",
    "a fast-paced environment where change is treated as opportunity,",
    "not obstacle — with teams that move quickly and decide clearly.",
    "📚",
    "Learning & growth built-i",
    "Structured career paths, mentorship, and continuous development programs keep you",
    "future-ready — from foundational consulting skills to advanced digital, Lean,",
    "and leadership capabilities.",
    "Think curated learning journeys, not random trainings — designed so every project stretches",
    "you just enough.",
    "🌐",
    "Collaboratio",
    "beyond borders",
    "Work with global talent pools, industry leaders, and ecosystem partners — across regions,",
    "sectors, and disciplines.",
    "🏁",
    "Ownership from day one",
    "We reward initiative, innovation, and accountability. You’ll get real responsibility",
    "early, with the support to tur",
    "good ideas into visible outcomes.",
    "n",
    "Our values i",
    "actio",
    "What we stand for whe",
    "we show up to work.",
    "These are the principles that shape how we think, decide, and deliver — with clients,",
    "with each other, and i",
    "the way we grow the firm.",
    "🎯",
    "Purpose",
    "Anchor every decisio",
    "i",
    "long-term impact — for our clients, their stakeholders,",
    "and the communities we serve.",
    "⚡",
    "Agility",
    "Adapt fast, act smart. We test, learn, and move quickly without losing",
    "discipline or clarity.",
    "🤝",
    "Collaboratio",
    "Harness collective intelligence — across teams, clients, and partners —",
    "to solve problems that matter.",
    "🔐",
    "Trust",
    "Deliver with integrity, transparency, and follow-through so people ca",
    "rely",
    "o",
    "what we say and do.",
    "⭐",
    "Excellence",
    "Always go the extra mile — i",
    "the quality of our thinking, our execution,",
    "and the experience we create.",
    "n",
    "Career pathways",
    "Where you ca",
    "grow with us",
    "We’re always looking for problem-solvers, innovators, and leaders who want to build",
    "real capability — and deliver outcomes that last.",
    "Impact",
    "Learning",
    "Ownership",
    "Client-side",
    "📈",
    "Growth & Strategy Consulting",
    "Shape strategic direction, operating models, and executio",
    "roadmaps with measurable outcomes.",
    "Strategy • TOM • Governance",
    "🤖",
    "Tech-Enabled Transformatio",
    "Enable digital transformatio",
    "through data, automation, AI, and moder",
    "platforms — grounded i",
    "execution.",
    "Digital • Analytics • AI",
    "🌿",
    "ESG & Sustainability",
    "Build resilient, responsible organisations through ESG strategy, reporting, and sustainability programs.",
    "ESG • Reporting • Value",
    "⚙️",
    "Operational Excellence",
    "Drive productivity, quality, and speed using Lean, continuous improvement, and Industry 4.0 thinking.",
    "Lea",
    "• CI • Performance",
    "🧩",
    "Business Process Advisory",
    "Desig",
    "better processes, shared services, and governance — building systems that scale.",
    "Shared Services • BPM • KPIs",
    "🧭",
    "Ope",
    "Roles Across Functions",
    "We also hire across research, delivery, program management, and capability building.",
    "PMO • Delivery • Enablement",
    "n",
    "Your journey with us",
    "From day one, you’re part of the real work.",
    "From Day 1, you’ll be o",
    "live projects, mentored by global experts, and equipped",
    "with tools that connect strategy to executio",
    "— so you see the impact of your work",
    "i",
    "real outcomes, not just presentations.",
    "Ready to create something extraordinary?",
    "Joi",
    "us to transform strategy into results that last.",
    "Apply now →",
    "View role pathways",
    "No perfect CV? If you’re curious, driven, and collaborative, we still want to hear from you."
  ]
} as const;
