// DO NOT EDIT THIS CONTENT.
// This content is locked and must match the original website exactly.
// Only explicit written approval permits changes.
export const navigationFooter = {
  "key": "navigationFooter",
  "name": "Navigation and Footer",
  "route": "",
  "currentUrl": "https://mediumpurple-ant-531485.hostingersite.com/",
  "source": "10-header.txt",
  "image": "",
  "title": "Follow us:",
  "description": "info@yourbrand.com",
  "lines": [
    "Follow us:",
    "info@yourbrand.com",
    "+91 98765 43210",
    "Home",
    "About",
    "Services ▾",
    "Services Portfolio",
    "Strategy & Operations services by theme",
    "All Services",
    "Overview of our Strategy & Operations offerings across growth, operations and corporate functions.",
    "Growth & Transformatio",
    "Vision, strategy, operating models and growth executio",
    "for leaders and boards.",
    "Operational Excellence",
    "Cost, quality and productivity improvement through Lean, Ge",
    "AI and digital.",
    "Process Advisory",
    "Process design, metrics, analytics and QMS / TQM maturity assessments.",
    "Service Delivery",
    "Customer strategy, journeys and service delivery desig",
    "& measurement.",
    "Corporate Functio",
    "Transformatio",
    "From fragmented support functions to a",
    "integrated, data-drive",
    "corporate backbone.",
    "Strategy & Operations",
    "Designing growth, margi",
    "and resilience together",
    "Our services spa",
    "the full Strategy & Operations stack – from growth strategy and operating models",
    "to Lean, digital, and corporate functio",
    "transformatio",
    "– with measurable impact.",
    "Growth",
    "OpEx",
    "Process",
    "Customer",
    "Corporate Backbone",
    "View all services",
    "Discuss your priorities →",
    "Industries ▾",
    "Industry Pages",
    "Choose a sector to explore solutions",
    "Pharmaceutical",
    "Quality, compliance, throughput, cost and reliability.",
    "Manufacturing",
    "Lea",
    "systems, productivity, stable operations at scale.",
    "Healthcare",
    "Patient experience, capacity, and operational resilience.",
    "Insurance",
    "Claims speed, trust, cost discipline, digital enablement.",
    "Aerospace & Defence",
    "High-stakes delivery with quality and traceability.",
    "Automotive",
    "EV shift, supply volatility, productivity, speed.",
    "Global Capability Centers",
    "Value platforms, governance, productivity at scale.",
    "Educatio",
    "Future-ready workforce, capability and ecosystem impact.",
    "Featured",
    "Explore transformatio",
    "playbooks by sector",
    "Practical, system-level work across strategy, operating models, digital enablement,",
    "capability building, and measurable outcomes.",
    "Strategy",
    "Operating Model",
    "Digital",
    "ESG",
    "OpEx",
    "Talk to us",
    "Request consultatio",
    "→",
    "Career",
    "Contact",
    "Services",
    "Book Consultatio",
    "Y",
    "YourBrand Consulting",
    "Menu",
    "Home →",
    "About →",
    "Services ⌄",
    "All Services",
    "Growth & Transformatio",
    "Operational Excellence",
    "Process Advisory",
    "Service Delivery",
    "Corporate Functio",
    "Transformatio",
    "Industries ⌄",
    "Pharmaceutical",
    "Manufacturing",
    "Healthcare",
    "Insurance",
    "Aerospace & Defence",
    "Automotive",
    "GCC",
    "Educatio",
    "Career →",
    "Contact →",
    "View Services",
    "Book Consultatio",
    "→",
    "n",
    "Follow us :",
    "n",
    "n\t\t\t\t\t\tFacebookn",
    "n",
    "n\t\t\t\t\t\tTwittern",
    "n",
    "n\t\t\t\t\t\tYoutuben",
    "n",
    "n",
    "n",
    "n\t\t\t\t\t\t\t\t\t\tinfo@aretepartners.comn",
    "n",
    "n",
    "n",
    "n\t\t\t\t\t\t\t\t\t\t+91 9876543210n",
    "n",
    "n",
    "n",
    "n",
    "n",
    "n\t\t\t\t\t\t\t\t\t\t+1 (212)-695-1962n",
    "n",
    "n",
    "n\t\t\t\t\t\t\t\t\t\tinfo@elementskit.comn",
    "n",
    "n\t\t\t\t\t\t\t\t\t\t463 7th Ave, NY 10018, USAn",
    "n",
    "n",
    "n",
    "n",
    "n",
    "n",
    "n",
    "n",
    "n",
    "n",
    "n",
    "Home",
    "About",
    "n",
    "Team",
    "Services",
    "Products",
    "Industries",
    "Trainings",
    "Career",
    "Contact Us",
    "X",
    "n",
    "n",
    "n"
  ]
} as const;
